### ISSUE TITLE
Can select non existing cells on rowCount/columnCount change

### ISSUE THREAD

**Issue by GeorgS** [rowsncolumns/grid#110]
When changing the `rowCount` or `columnCount` key of a sheet dynamically I am able to select fields that don't exist anymore.
I've created a quick example here: https://codesandbox.io/s/rnc-example-count-tfj1v

![Screenshot 2020-08-12 at 14 24 01](https://user-images.githubusercontent.com/827885/90014517-81969500-dca7-11ea-8d38-cec30e974fd0.png)

**Comment by rmdort** [comment]
Thanks. Taking a look at it now

**Comment by rmdort** [comment]
Fixed this issue in the new release.
