### ISSUE TITLE
small columnCount and rowCount cause UI issue

### ISSUE THREAD

**Issue by alaarab** [rowsncolumns/grid#112]
when using a small columnCount and rowCount (which can be useful to show small amounts of data in a grid) comes with a UI issue, there is extra space and the scroll bars are far away. The minHeight is too large for this, and I cannot seem to get around it, even when setting the container to be smaller.

![image](https://user-images.githubusercontent.com/1730921/90165464-89a91000-dd4d-11ea-854b-8ed3993eda18.png)

In this example, I am not showing any formula or status bars, because the specific sheet I am using this on does not need those features. Possibly being able to control the max size with a container would be good.

**Comment by rmdort** [comment]
Are you wrapping it in a flex container. SpreadSheet automatically occupies the whole flex container.

Or you could set `minHeight`, `<SpreadSheet minHeight={200} />`

or try this

````
<div style={{
  display: 'flex',
  flex: 1,
  minWidth: 0,
}}>
  <SpreadSheet />
</div>
````

**Comment by alaarab** [comment]
I now understand the functionality a bit better. I was able to change the width of the container, and the minHeight of the container manually to reflect those changes. The last example you provided didn't seem to work for me though. 

Here is a follow up question - is it possible to get the 'Height'/'Width' of the Sheet(+any active bars), this way I could dynamically resize the container to perfectly fit the contents of the sheet if the contents are too little? ( I know when resizing a row or column, the height/width of the sheet will change )

**Comment by rmdort** [comment]
If you want to resize grid based on rows, columns, you can set minHeight by calculating height of rows

https://codesandbox.io/s/agitated-hoover-ld83j?file=/src/App.js

I dont think this logic belongs in SpreadSheet, as the Bottom sheet bar will jump when user switches sheets.

I see that you are not really after spreadsheet functionality, why dont u use `@rowsncolumns/grid` . That is better suited to your needs.

Example of Grid
https://codesandbox.io/s/gifted-fire-ky8gf?file=/src/App.js:0-258

**Comment by alaarab** [comment]
Thank you. I think I can make way with the idea from the first demo. Thank you for providing this.

I think SpreadSheet is still right for me since I'm making use of onChangeCells callbacks, which I don't think 'grid' alone has. Overall, I like the full-feature set and Excel feel of Spreadsheet.

I will close this issue, and consider Grid in the case it could also be useful for me.

**Comment by rmdort** [comment]
> Thank you. I think I can make way with the idea from the first demo. Thank you for providing this.
> 
> I think SpreadSheet is still right for me since I'm making use of onChangeCells callbacks, which I don't think 'grid' alone has. Overall, I like the full-feature set and Excel feel of Spreadsheet.
> 
> I will close this issue, and consider Grid in the case it could also be useful for me.

Grid is stateless. you have to manage your state, and use `itemRenderer` to render cells

https://github.com/rowsncolumns/grid/tree/master/packages/grid#usage
