### ISSUE TITLE
Copy and Paste or Fill over validations/locked etc

### ISSUE THREAD

**Issue by alaarab** [rowsncolumns/grid#113]
When a cell has data validation or locked, it is possible to copy and paste a value into the cell or fill over it, which defeats the purpose of these features.

**Comment by rmdort** [comment]
Yes. am aware of this. Should be a simple fix. Will update

**Comment by rmdort** [comment]
Pushed a fix for this. Locked cells or sheet cannot be modified

**Comment by alaarab** [comment]
Looks good.
