### ISSUE TITLE
npm peer support warnings for @rowsncolumns/export

### ISSUE THREAD

**Issue by 313v** [rowsncolumns/grid#132]
I keep getting this warning when i install on npm:
`@rowsncolumns/export@6.1.3 requires a peer of @rowsncolumns/spreadsheet@^1.4.11 but none is installed. You must install peer dependencies yourself`

i  think its because of this mismatch in the [package.json?](https://github.com/rowsncolumns/grid/blob/master/packages/export/package.json) (i'm not an npm expert)

 `
"peerDependencies": {
    "@rowsncolumns/spreadsheet": "^1.4.11"
  },
  "devDependencies": {
    "@rowsncolumns/spreadsheet": "^6.1.3"
  }
`

**Comment by 313v** [comment]
now i get this warning:

`@rowsncolumns/export@6.1.5 requires a peer of @rowsncolumns/spreadsheet@>=^6.0.0 but none is installed. You must install peer dependencies yourself.`

i do have spreadsheet installed - 6.14
everything runs just fine too

**Comment by rmdort** [comment]
Oops.. used incorrect version number for peer. Fixed.
