### ISSUE TITLE
Auto complete other columns

### ISSUE THREAD

**Issue by phoique** [rowsncolumns/grid#17]
Hello, when you type 1-2-3 or 14:30, 14:40 in Excel and drag it down, it automatically increases the value and saves it. When I tested this on the examples on the website I couldn't. is it possible for me to do this?

**Comment by rmdort** [comment]
`useSelection` hook has a callback `onFill` which you can consume to update your data

https://github.com/rowsncolumns/grid/blob/master/packages/grid/src/hooks/useSelection.ts#L59
