### ISSUE TITLE
After Zoom In or Zoom Out the tooltip and contextMenu's position is wrong.

### ISSUE THREAD

**Issue by JimZhang1028** [rowsncolumns/grid#19]
After Zoom In or Zoom Out the tooltip and contextMenu's position is wrong.

**Comment by rmdort** [comment]
You mean browser zoom in using `ctrl+(+/-)` ? Seems to be working fine in https://rmdort.github.io/konva-grid/?path=/story/grid--with-tooltip

**Comment by rmdort** [comment]
I guess the easy thing to do is hide the tooltip if window resizes And show it when user hovers a cell

**Comment by JimZhang1028** [comment]
No,I use the toolbar's zoom in and on the 5:1 to call the contextMenu.
![批注 2020-06-05 151951](https://user-images.githubusercontent.com/37504081/83848234-1a58e380-a740-11ea-9d1b-dc5d14472a27.png)

**Comment by rmdort** [comment]
Ah. Thats because storybook uses `zoom` attribute instead of browser zoom. Positioning will break. Dont think we want to support this. You could zoom using `ctrl/cmd + (+/-)`

**Comment by rmdort** [comment]
I have added this a feature request in https://github.com/rmdort/konva-grid/projects/1#card-39550248

**Comment by rmdort** [comment]
Done - https://github.com/rowsncolumns/grid/blob/master/packages/grid/src/Grid.tsx#L474
