### ISSUE TITLE
Grid doesn't work, throw some error

### ISSUE THREAD

**Issue by tomorrowcheng** [rowsncolumns/grid#21]
Grid doesn't work, throw some error
<img width="673" alt="image" src="https://user-images.githubusercontent.com/42925114/219945605-997a96c4-5043-4fec-bd60-52043433b314.png">

Is it that because I used in React 18.2.0 ? like this [https://github.com/rowsncolumns/grid/issues/14](issues14)?

**Comment by rmdort** [comment]
Could you try now . This PR #22 has added React 18+ compatiblity.

**Comment by tomorrowcheng** [comment]
> Could you try now . This PR #22 has added React 18+ compatiblity.

Thanks !
