### ISSUE TITLE
Fill-Handle does not work with React 18

### ISSUE THREAD

**Issue by GeorgS** [rowsncolumns/grid#23]
The Fill-Handle does not seem to work anymore with React 18. I've started debugging this and noticed that [fillSelection](https://github.com/rowsncolumns/grid/blob/master/packages/grid/src/hooks/useSelection.ts#L1219) is null when it is checked. The [setFillSelection callback](https://github.com/rowsncolumns/grid/blob/master/packages/grid/src/hooks/useSelection.ts#L1209-L1214) (which should populate the var) triggers too late.

The rest of the function could either be moved inside the `setFillSection(prev => ...` callback or the fillSelection state is tracked in a ref as well.

I'll gladly provide a PR but want to discuss which approach is preferred.

**Comment by rmdort** [comment]
Hmm.. Works for me here - https://codesandbox.io/s/fancy-firefly-3ocbgp?file=/src/App.tsx 

What exactly is the bug ?

**Comment by GeorgS** [comment]
Sorry, I wasn't very precise. What's not working is populating fields with the same value to the right or down by dragging the handle on the current selection (`onFill` of the `useSelection` hook).

I can reproduce it with the "EditableGrid" storybook example: https://codesandbox.io/s/youthful-engelbart-b7nt8y

![Screenshot 2023-03-06 at 16 05 44](https://user-images.githubusercontent.com/827885/223150220-00ac1019-602a-426d-88d5-6993b2623d70.png)

**Comment by rmdort** [comment]
Ah ok. Fixed in 9.0.4

**Comment by GeorgS** [comment]
Awesome, thanks!
