### ISSUE TITLE
stop demo animation

### ISSUE THREAD

**Issue by 3052** [rowsncolumns/grid#29]
the animation here is really annoying:

https://www.rowsncolumns.app/demo

is it possible to disable?

**Comment by rmdort** [comment]
Hi, Its realtime collaboration. I am not animating anything. Sorry for the trouble, Can you try the demo another time

**Comment by 3052** [comment]
right, but it might be useful to have a single person demo and a multi person demo. its kind of hard to get a feel for the product when its constantly being changed by other people. It would be like going to buy a TV and meanwhile 10 other people are grabbing the remote from you, standing in front of the TV, changing the channel, etc.

**Comment by rmdort** [comment]
Totally understand. Here is a single user demo - https://www.rowsncolumns.app/demo?collab=false
