### ISSUE TITLE
[question] Can I set variables in formula?

### ISSUE THREAD

**Issue by joneldiablo** [rowsncolumns/grid#3]
Hi good day! this project looks amazing cheers!!!
I have some questions:

* Can I set custom variables to be evaluated in cell? for example `=A1*MY_OWN_VARIABLE`
* Can I eval some formula outsite a table, server side, for example, I want to make a website with an administrator, with this table and other site which show the public data, then, if I put some formula in one cell, how could I get the evaluated value, eval before sync with the server or could I sync the raw value of cell (the formula) and eval from server? this question is because I thinking some user, some one, me, could put a formula with something like "if date less than"... so meabe need eval at the momento of serve the final data
* Can I make alias for select value from other cell? I'm thinking allow put a formula in one cell but I want restrict to select only other cells of the same row, something like `=$B$this * .8` or even better `=$price * .8` (where $price is an alias for column B)
* finally XD can I put some basic nodes like `<button></button>, <img />, <a></a>` in custom cell rendered?

thank you
good day!

**Comment by rmdort** [comment]
Spreadsheet is no longer available as it has been acquired.
