### ISSUE TITLE
[DOCUMENTATION] getting started and related links

### ISSUE THREAD

**Issue by kevbarns** [rowsncolumns/grid#5]
Trying to install rowsncolumn package following the get started page but the `yarn add @rowsncolumns/spreadsheet` doesn't work. 

I found out the the repository itself on github no longer exist as well, or might have been changed to this one, grid ? 

Thanks for your feedback, the tool seems amazing, hope it's still available. 

Kevin

**Comment by rmdort** [comment]
Hi,

Sorry to say that the product has been acquired and no longer available for
licensing. Thank you for the interest.

Warm regards
vinay

**Comment by bkniffler** [comment]
What about this library (grid)? Is it also going to get removed? @rmdort

**Comment by rmdort** [comment]
No. Grid is open source. MIT licensed.

**Comment by stephensilber** [comment]
Is it possible to add this note to the website? I spent longer than I'd like to admit trying to get the spreadsheet package installed until I stumbled upon this issue.
