### ISSUE TITLE
Selecting a cell, then typing a number double types

### ISSUE THREAD

**Issue by maxbla** [rowsncolumns/grid#61]
Steps to reproduce:
1. open [demo](https://rowsncolumns.app/demo)
2. *single* click cell A1 (or any cell, empty or not)
3. type the number "1" (or any letter or number)
4. cell now contains "11"

System info: Firefox 78.0.2 on Linux, using an adblocker.

**Comment by rmdort** [comment]
Works fine on firefox on Mac/Window. Let me try it on Linux.

**Comment by rmdort** [comment]
Fixed this. 21f83ac5eb58297645e827d12126c6386349813c

Thanks for reporting.
