### ISSUE TITLE
Hotkeys on firefox

### ISSUE THREAD

**Issue by rmdort** [rowsncolumns/grid#62]
Hotkeys in firefox don't seem to work properly.

Pgup/Pgdn, ctrl-down etc just inputs the keycode on my machine.

**Comment by rmdort** [comment]
Page Up/Down is implemented. 

Todo

1. Ctrl + down = Navigate to first blank cell downwards
2. Ctrl + down = Navigate to first blank cell upwards

**Comment by wbercx** [comment]
In Chrome, pressing certain keys _on a selected cell that already has content_ replaces that content with the string name of the key.

For example, pressing:
- `Delete` prints "Delete"
- `Scroll Lock` prints "ScrollLock"
- as above for "Insert"
- `F1` prints "AudioVolumeMute"
- `F6` prints "MediaTrackNext"
- `F10` prints "F10"

![image](https://user-images.githubusercontent.com/2244710/88365278-d9d52800-cdc8-11ea-8879-de138cda9efd.png)

**Comment by rmdort** [comment]
Yep. Certain keys needs to be in exclude list to prevent activating edit mode. I have fixed it in f805fd43c466e9a1e0d81bf5ea2e5cb0fec64996

**Comment by rmdort** [comment]
This is now supported f83c28a0b7bd463a49578d54df79995f2a3a793f

cmd/ctrl + up/down will select cells in a data region. Works for cell selection too.
