### ISSUE TITLE
Allow custom names for rows and columns

### ISSUE THREAD

**Issue by loredanacirstea** [rowsncolumns/grid#76]
This would open new use cases, like database data display & processing. Otherwise, you are limiting your market.

**Comment by rmdort** [comment]
Does excel allow this?

**Comment by loredanacirstea** [comment]
No, but https://github.com/TonyGermaneri/canvas-datagrid was used for example for cleaning up/filtering data for AI training. We want to know what is your plan for the future with the spreadsheet - if it will also cover this (database) direction.

**Comment by rmdort** [comment]
My plan is to keep the features inline with Google Sheets and MS Excel.

Switching to custom header cell will let you do that

https://codesandbox.io/s/quiet-hooks-d4ldg?file=/src/App.js

**Comment by rmdort** [comment]
Hope this issue can be closed. Please reopen if needed
