### ISSUE TITLE
Displaying JSON objects recursively

### ISSUE THREAD

**Issue by loredanacirstea** [rowsncolumns/grid#77]
In a similar vein with https://github.com/rowsncolumns/grid/issues/76

Similar to https://observablehq.com/@khron/sheet - the example at the bottom.

![Screen Shot 2020-07-28 at 6 33 45 PM](https://user-images.githubusercontent.com/4785356/88687568-1d999b80-d101-11ea-92c5-28e1d2828425.png)

**Comment by rmdort** [comment]
We are going to support excel outline - https://github.com/rowsncolumns/grid/issues/39

**Comment by loredanacirstea** [comment]
I have not used excel's outline, so I don't know if it is recursive. Does it fully solve the JSON display issue?

**Comment by rmdort** [comment]
It looks like this. You can group columns and rows. But a tree like grid is not in our roadmap

![image](https://user-images.githubusercontent.com/118231/88691613-a7605d80-d12f-11ea-8c4b-7e2f3701858c.png)

**Comment by rmdort** [comment]
Grid  primitive supports tree table also. I

https://rowsncolumns.github.io/grid/?path=/story/treetable--tree-table

If i get some time, i can put up a demo for displaying hierarchical JSON. If you have any sample data, please do send

**Comment by loredanacirstea** [comment]
I did not see that in the Storybook - my mistake, I should have paid more attention.
This is great, it solves the issue. No need for a demo. Thank you.

**Comment by rmdort** [comment]
The treetable code might be a bit unreadable :P Old demo
