### ISSUE TITLE
Multiple split for sheet rows & columns

### ISSUE THREAD

**Issue by loredanacirstea** [rowsncolumns/grid#78]
Split the sheet while preserving scrolling ability on both sides. 
Support for multiple splits (>= 2) - similar to how you can split/partition a terminal/text editor.

**Comment by rmdort** [comment]
It does not need to be part of SpreadSheet. But the `Grid`  can be used for this.

https://github.com/rowsncolumns/grid/tree/master/packages/grid

**Comment by loredanacirstea** [comment]
I did not see multiple splitting in `Grid`, so I assume you are suggesting to control the multiple splitting from parent components, using multiple `Grid`s. Am I correct?

**Comment by rmdort** [comment]
A demo with Grid Component. 

https://codesandbox.io/s/patient-flower-peutr?file=/src/App.js

This is not supported in SpreadSheet, as it does not have multiple grids. We will support multiple views.. Eg: Filters views similar to Google sheets

**Comment by loredanacirstea** [comment]
Thank you. It meets my requirements.

**Comment by rmdort** [comment]
Great. Do note that this is just a plain grid. To add selection capabilities, you will need to use `useSelection` hook, `useEditable` for editing features. You can take a look at storybook to see how its done.
