### ISSUE TITLE
Navigation Issue - Horizontal Scroll too difficult (SHIFT functionality)

### ISSUE THREAD

**Issue by alaarab** [rowsncolumns/grid#82]
Google Sheets allows "'Shift' + Mouse Scroll" to support horizontal scrolling. 
Another way of navigating is to use "Mouse Middle Click + Move mouse around", but this also does not work.
The shift feature would be extremely useful in this tool as these common navigation features are missing.

**Comment by rmdort** [comment]
Shift + Mouse Scroll will work now.

Mouse middle click and move around does not work in Google Sheets or MS Excel on Mac. Will add it to the backlog.

**Comment by alaarab** [comment]
Nice work @rmdort, I can say shift is much more important than Mouse Middle Click / Move.

I can confirm that shift functionality is working when I'm on my Mac, but this doesn't seem to work from my Windows Machine.

**Comment by rmdort** [comment]
Yeah. When shift key is pressed, Scroll event is not firing on Windows Chrome. Not sure  how to fix this. Will need to see

**Comment by rmdort** [comment]
Fixed. Can you try now.

**Comment by alaarab** [comment]
It's working. Great Job :) This solves the main navigation issue, so I will close this issue.
