### ISSUE TITLE
useEditable: submitting the value with mouse click on another cell uses outdated onSubmit callback

### ISSUE THREAD

**Issue by dgrechka** [rowsncolumns/grid#9]
I use the `useEditable` hook. I provide `onSubmit` callback to it.

I noticed that when I submit with Enter key hit and with the navigating away from the edited cell (clicking on other cell) the behaviour is different.

Click on another cell results in outdated  onSubmit callback instance call (not the one provided in recent render, e.g. recent invocation of `useEditable`).

Possible cause for this is the dependency list of the `handleMouseDown` inside  `useEditable`.
https://github.com/rowsncolumns/grid/blob/master/packages/grid/src/hooks/useEditable.tsx#L819

```typescript
const handleMouseDown = useCallback(
    (e: React.MouseEvent<HTMLDivElement>) => {
      /* Persistent input, hides only during Enter key or during submit or cancel calls */
      if (!hideOnBlur) {
        return;
      }
      if (currentActiveCellRef.current) {
        if (isDirtyRef.current) {
          handleSubmit(currentValueRef.current, currentActiveCellRef.current);
        } else {
          handleCancel();
        }
      }
      initialActiveCell.current = undefined;
    },
    [hideOnBlur] //   <------------------------------- does this cause problem?
  );
```

`handleMouseDown` seems to be regenerated only on hideOnBlur change. Thus it captures very first `handleSubmit` (which in turn captures very first `onSubmit`)

**Comment by dgrechka** [comment]
The same issue may also apply for `handleKeyDown` handler implementation and `onDelete` user provided callback.
https://github.com/rowsncolumns/grid/blob/master/packages/grid/src/hooks/useEditable.tsx#L681

**Comment by rmdort** [comment]
Taking a look.

**Comment by rmdort** [comment]
yeah. i didnt add those dependencies in the hooks. Published new version, Can you verify.

**Comment by dgrechka** [comment]
Thanks. verifying.

**Comment by dgrechka** [comment]
Yes. the issue has gone.
Thanks for the immediate fix. much appreciated!

**Comment by rmdort** [comment]
There was a bug in onSubmit useCallback hook. Fixed.
