### ISSUE TITLE
State Reducer: ACTION_TYPE.UPDATE_CELLS returns wrong action object

### ISSUE THREAD

**Issue by westoncolemanl** [rowsncolumns/grid#94]
To Reproduce

```
      const stateReducer = (state: StateInterface, action: ActionTypes): StateInterface => {
        if (action.type === ACTION_TYPE.UPDATE_CELLS) {
          console.log(action)
          // returns
          // {
          //   changes: {},
          //   type: 'UPDATE_CELLS',
          //   undoable: false
          // }
        }

        return state
      }

      <SpreadSheet
        showFormulabar={false}
        showToolbar={false}
        allowNewSheet={false}
        showTabStrip={false}
        sheets={sheets}
        onChange={setSheets}
        initialColorMode={globalAny.darkTheme ? 'dark' : 'light'}
        ContextMenu={(props: ContextMenuComponentProps): ReactElement => MyContextMenu(props, institutions)}
        HeaderCellRenderer={HeaderCellRenderer}
        CellRenderer={CellRenderer}
        stateReducer={stateReducer}
      />
```

1. Changes Object is empty
2. The action is undoable, yet undoable = false

**Comment by rmdort** [comment]
Yep. UPDATE_CELLS is called when Calculation Engine returns results. Must have been an error. Made it undoable.

**Comment by westoncolemanl** [comment]
Thanks for the quick response. I pulled the latest version.

Can confirm undoable is no longer returned. 

**However, changes object is still empty.**

Keep up the good work man!

**Comment by rmdort** [comment]
Update cells is called to batch update cells with results from calculation engine. If there are no results, it will be empty.

Maybe you need to look for a different action to hook into. What are u trying to solve?

**Comment by westoncolemanl** [comment]
I'm not trying to solve anything at the moment. Just studying how this module works.

I've tried
1. Editing a single cell
2. Mass deleting from cells

But the changes object is always empty. How should I get it to show a value?

**Comment by rmdort** [comment]
`UPDATE_CELLS` is not dispatched when editing or deleting cells. Currently its only dispatched when we get results from Calculation engine for formulas like `=SUM(2,2)`

`DELETE_CELLS` is called when cells are deleted
`CHANGE_SHEET_CELL` is called when a single cell is edited

Just do a console.log in ur stateReducer to see which actions get called

**Comment by westoncolemanl** [comment]
Understood, thanks so much!
