### ISSUE TITLE
Support for self-updating data

### ISSUE THREAD

**Issue by nepsilon** [rowsncolumns/grid#95]
Hi,
I'm looking at the support for [formulas](https://rowsncolumns.app/docs/formula) and wondered if there is a way to automatically update the data returned once returned. Either via a websocket event or with a simple `setInterval()` function.

Thanks!

**Comment by rmdort** [comment]
Right now its not possible. But if i have to do it, i am thinking of this approach

````
const [ sheets, setSheets ] = useState(defaultSheets)
const [ tickingSubscriber, setTickingSubscriber ] = useState()
useEffect(() => {
  const ws = ws.connect()
  ws.on('data', (results) => {
    setSheets(// Update the sheets)
  })
}, [ tickingSubscriber ])
<SpreadSheet
  sheets={sheet}
  onChange={setSheets}
  formulas={{
    'GET_TICKING_DATA': (cell, arg) => {
      setTickingSubscriber(cell, arg.value)
    }
  }}
/>
````

The issue right now is that formulas does not have access to the `cell` position. So the websocket callback wont know which group of cells to update.

Tracking this issue here https://github.com/LesterLyu/fast-formula-parser/issues/18

**Comment by nepsilon** [comment]
Thanks for the prompt reply and detailed answer. Real-time data is impossible in Google Sheets (via custom function), so supporting this would be a massive plus for rowsncolumns.
Feel free to close this issue if you'd like to track this in https://github.com/LesterLyu/fast-formula-parser/issues/18

**Comment by rmdort** [comment]
I guess it is possible. I will need to do a breaking change for formulas, to pass cell position as first argument to custom formulas. Will update once i get around this.

**Comment by rmdort** [comment]
Now you can access cell context in formulas as the first argument. 

I have done an example of real-time data here - https://codesandbox.io/s/dazzling-chatelet-bv8bs?file=/src/App.js

I have used `setInterval`, but you could use websockets.

**Comment by nepsilon** [comment]
Thanks a ton, this helps a lot! I played with the example, I see how I could plug in websocket I think. But do you know how to keep the cells referencing an auto-updating cell show the last refreshed value, and not just the value at the time of the formula evaluation?

**Comment by rmdort** [comment]
Sure. I had to expose `onCalculate` in `ref` so you can trigger calculation. Updated codesandbox.

**Comment by rmdort** [comment]
Closing this. Reopen if you have any questions.
