### ISSUE TITLE
Copy by dragging a single cell via its border doesn't work in vertical direction

### ISSUE THREAD

**Issue by mat-overclockers** [rowsncolumns/grid#98]
It works well by dragging the border left and right, but the selection doesn't follow any vertical direction. It works though if two or more cells are selected.

Doesn't work - Single cell selected and border dragged vertically:
![rowsncolumns](https://user-images.githubusercontent.com/3847700/89669183-45e28080-d8df-11ea-9506-5fcb42b031b5.png)

Works - Two cells selected and border dragged vertically:
![rowsncolumns - 2 cols selected](https://user-images.githubusercontent.com/3847700/89669668-28fa7d00-d8e0-11ea-8da2-914aecc54434.png)

Browser:
- Chrome 84.0.4147.105/Windows 10
- Firefox 79/Windows 10

Thank you and if you need further information, please let me know.

**Comment by rmdort** [comment]
Hmm. Works fine for me. Will test on  windows chrome and let u know

**Comment by mat-overclockers** [comment]
We just found out that this was a mistake from our side. The columns can only be copied either horizontally OR vertically. It feels a bit off, but is exactly the same behaviour as Excel.
